"""
Base Pydantic schemas for MLZero.
"""

from typing import Any

from pydantic import BaseModel, Field


class AgentTask(BaseModel):
    """Schema representing a task given to an agent."""
    task_id: str = Field(..., description="Unique identifier for the task.")
    description: str = Field(..., description="Description of the task.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional task metadata.")


class AgentResponse(BaseModel):
    """Schema representing a response from an agent."""
    task_id: str = Field(..., description="Task identifier this response corresponds to.")
    status: str = Field(..., description="Status of the task (e.g., success, failure).")
    output: Any = Field(None, description="The output generated by the agent.")
    errors: list[str] | None = Field(default_factory=list, description="Any errors encountered.")
